services:
  # MONITORING STACK
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    restart: unless-stopped
    command: 
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.external-url=/prometheus/"
      - "--web.route-prefix=/prometheus/"

  node_exporter:
    image: quay.io/prometheus/node_exporter:latest
    container_name: node_exporter
    command: 
      - "--path.rootfs=/host"
    pid: host
    restart: unless-stopped
    volumes:
      - "/:/host:ro,rslave"
      
  # mysqld_exporter:

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.45.0

  grafana:
    image: grafana/grafana-oss:latest

  # LOGGING STACK
  loki:
    image: grafana/loki:latest

  promtail:
    image: grafana/promtail:latest

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local