services:
  # MONITORING STACK
  prometheus:
    image: prom/prometheus:latest

  node_exporter:
    image: quay.io/prometheus/node_exporter:latest

  # mysqld_exporter:

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.45.0

  grafana:
    image: grafana/grafana-oss:latest

  # LOGGING STACK
  loki:
    image: grafana/loki:latest

  promtail:
    image: grafana/promtail:latest

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local